### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by ghost** [kkdai/tm#1]
Hi i installed the lib via go get github.com/kkdai/tm but when I try to run the sample code I get following error:
`/Users/noby/go/src/github.com/norbertfuhs/turing > go run main.go
# command-line-arguments
./main.go:4: imported and not used: "github.com/kkdai/tm"
./main.go:8: undefined: NewTM
./main.go:21: undefined: MoveRight
./main.go:22: undefined: MoveLeft
./main.go:23: undefined: MoveLeft
./main.go:24: undefined: MoveRight
./main.go:32: undefined: fmt in fmt.Println`

Is there a quick fix for this?

**Comment by kkdai** [comment]
@norbertfuhs Thx, Just update my README and add "example" folder. you can build it  directly.
